name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: valgrind
      run: |
        apt install valgrind -y
        make test
        valgrind --leak-check=full --error-exitcode=1 ./build/test
